#!/bin/bash
# Copyright (c) 2014 Michael Homer
#
# Permission to use, copy, modify, and/or distribute this software for
# any purpose with or without fee is hereby granted, provided that the
# above copyright notice and this permission notice appear in all
# copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

GITALYSE_LIBRARY=y
source $(dirname "$0")/gitalyse

declare -A authorCount
declare -A authorLength
declare -a names
maxlen=0
total=0
while read count name
do
    should_ignore_author "$name" && continue
    total=$((total + count))
    names=(${names:+"${names[@]}"} "$name")
    authorCount[$name]=$count
    len=$(wc -m <<<"$name")
    authorLength[$name]=$len
    if [[ $len -gt $maxlen ]]
    then
        maxlen=$len
    fi
done < <(git log --pretty=format:%aN ${1:+"$1"}|sort|uniq -c|sort -gr)

printf "Author %$((maxlen-8))s Commits  Proportion\\n" ""
for name in "${names[@]}"
do
    count=${authorCount[$name]}
    len=${authorLength[$name]}
    pc=$(bc <<<"scale=2;$count*100/$total")
    printf "%s %$((maxlen-len))s %'6i    %# 7.2f%%\\n" "$name" "" "$count" "$pc"
done
printf "%$((maxlen))s %'6i    %# 7.2f%%\\n" "" "$total" "100"
