#!/bin/bash
# Copyright (c) 2014 Michael Homer
#
# Permission to use, copy, modify, and/or distribute this software for
# any purpose with or without fee is hereby granted, provided that the
# above copyright notice and this permission notice appear in all
# copies.
#
# THE SOFTWARE IS PROVIDED "AS IS" AND THE AUTHOR DISCLAIMS ALL
# WARRANTIES WITH REGARD TO THIS SOFTWARE INCLUDING ALL IMPLIED
# WARRANTIES OF MERCHANTABILITY AND FITNESS. IN NO EVENT SHALL THE
# AUTHOR BE LIABLE FOR ANY SPECIAL, DIRECT, INDIRECT, OR CONSEQUENTIAL
# DAMAGES OR ANY DAMAGES WHATSOEVER RESULTING FROM LOSS OF USE, DATA OR
# PROFITS, WHETHER IN AN ACTION OF CONTRACT, NEGLIGENCE OR OTHER
# TORTIOUS ACTION, ARISING OUT OF OR IN CONNECTION WITH THE USE OR
# PERFORMANCE OF THIS SOFTWARE.

if [ ${BASH_VERSINFO[0]} -lt 4 ]
then
    echo "gitalyse requires Bash 4.0 or newer." >&2
    exit 1
fi

declare -A ignore_authors
declare -a ignore_files
ignore() {
    type=$1
    shift
    rest=$(echo $@)
    if [ "$type" = "file" ]
    then
        ignore_files=(${ignore_files:+"${ignore_files[@]}"} "$rest")
    elif [ "$type" = "author" ]
    then
        ignore_authors["$rest"]=y
    fi
}

should_ignore_author() {
    [ "${ignore_authors[$1]}" ] && return 0
    return 1
}

if [ "$GITALYSE_LIBRARY" ]
then
    repo=$(git rev-parse --show-toplevel 2>/dev/null) || {
        echo "Error: run gitalyse inside a git repository." >&2
        exit 1
    }
    [ -e "$repo/.gitalyse" ] && source $repo/.gitalyse
    return
fi

if [ -e "$(dirname "$0")/gitalyse-lines" ]
then
    COMMAND_PATH=$(dirname "$0")/
fi

cmd="$1"
shift
case "$cmd" in
    lines)
        exec ${COMMAND_PATH}gitalyse-lines "$@"
        ;;
    authors)
        exec ${COMMAND_PATH}gitalyse-authors "$@"
        ;;
    types)
        exec ${COMMAND_PATH}gitalyse-types "$@"
        ;;
    about|--version)
        echo "gitalyse computes statistics about the history of a git repository."
        echo "Written by Michael Homer"
        ;;
    help|--help)
        echo "Usage: $0 COMMAND [RANGE]"
        echo "Commands:"
        echo "  authors [RANGE]"
        echo "    Computes statistics on number of commits by each author."
        echo "  lines [RANGE]"
        echo "    Computes statistics on lines added by each author."
        echo "  types [--commits|--files|--commit-percent|--file-percent] [RANGE]"
        echo "    Computes statistics on changes to each type of file."
        echo
        echo "If RANGE is provided, only commits in this range will be"
        echo "analysed. See git rev-parse --help for formatting details."
        echo
        echo "gitalyse's analyses can be configured with a .gitalyse file"
        echo "in the repository root. It supports these entries:"
        echo "  ignore file PATH"
        echo "    Ignores changes to file PATH."
        echo "  ignore author NAME"
        echo "    Ignores commits by the named author."
        ;;
    *)
        echo "Usage: $0 (lines | authors)"
        echo "gitalyse computes some statistics about your git history."
        exit 1
esac
